import { readFile } from "fs/promises";
import { OpenAPIV3 } from "openapi-types";
import { getModel as getModelV3 } from "../../src/parse/models/v3";
import invariant from "tiny-invariant";

async function loadSpecFromFixtureFile(filePath: string): Promise<OpenAPIV3.Document | undefined> {
  const rawFile = await readFile(filePath, "utf8");

  return JSON.parse(rawFile) as OpenAPIV3.Document;
}

test("getModel with GitHub metadata schema", async () => {
  const doc = await loadSpecFromFixtureFile("./tests/fixtures/specs/v3/github.json");

  invariant(doc, "doc should not be null");

  const model = getModelV3(doc, "Metadata", {
    title: "metadata",
    description:
      "User-defined metadata to store domain-specific information limited to 8 keys with scalar values.",
    type: "object",
    maxProperties: 8,
    additionalProperties: {
      nullable: true,
      anyOf: [
        {
          type: "string",
        },
        {
          type: "number",
        },
        {
          type: "boolean",
        },
      ],
    },
  });

  expect(model).toMatchInlineSnapshot(`
    Object {
      "base": "any",
      "default": undefined,
      "deprecated": undefined,
      "description": "User-defined metadata to store domain-specific information limited to 8 keys with scalar values.",
      "enum": Array [],
      "enums": Array [],
      "examples": Array [],
      "exclusiveMaximum": undefined,
      "exclusiveMinimum": undefined,
      "export": "dictionary",
      "format": undefined,
      "imports": Array [],
      "isDefinition": false,
      "isNullable": false,
      "isReadOnly": false,
      "isRequired": false,
      "link": Object {
        "base": "any",
        "deprecated": undefined,
        "description": null,
        "enum": Array [],
        "enums": Array [],
        "examples": Array [],
        "exclusiveMaximum": undefined,
        "exclusiveMinimum": undefined,
        "export": "any-of",
        "format": undefined,
        "imports": Array [],
        "isDefinition": false,
        "isNullable": true,
        "isReadOnly": false,
        "isRequired": false,
        "link": null,
        "maxItems": undefined,
        "maxLength": undefined,
        "maxProperties": undefined,
        "maximum": undefined,
        "minItems": undefined,
        "minLength": undefined,
        "minProperties": undefined,
        "minimum": undefined,
        "multipleOf": undefined,
        "name": "",
        "pattern": undefined,
        "properties": Array [
          Object {
            "base": "string",
            "default": undefined,
            "deprecated": undefined,
            "description": null,
            "enum": Array [],
            "enums": Array [],
            "examples": Array [],
            "exclusiveMaximum": undefined,
            "exclusiveMinimum": undefined,
            "export": "generic",
            "format": undefined,
            "imports": Array [],
            "isDefinition": false,
            "isNullable": false,
            "isReadOnly": false,
            "isRequired": false,
            "link": null,
            "maxItems": undefined,
            "maxLength": undefined,
            "maxProperties": undefined,
            "maximum": undefined,
            "minItems": undefined,
            "minLength": undefined,
            "minProperties": undefined,
            "minimum": undefined,
            "multipleOf": undefined,
            "name": "",
            "pattern": undefined,
            "properties": Array [],
            "template": null,
            "type": "string",
            "uniqueItems": undefined,
          },
          Object {
            "base": "number",
            "default": undefined,
            "deprecated": undefined,
            "description": null,
            "enum": Array [],
            "enums": Array [],
            "examples": Array [],
            "exclusiveMaximum": undefined,
            "exclusiveMinimum": undefined,
            "export": "generic",
            "format": undefined,
            "imports": Array [],
            "isDefinition": false,
            "isNullable": false,
            "isReadOnly": false,
            "isRequired": false,
            "link": null,
            "maxItems": undefined,
            "maxLength": undefined,
            "maxProperties": undefined,
            "maximum": undefined,
            "minItems": undefined,
            "minLength": undefined,
            "minProperties": undefined,
            "minimum": undefined,
            "multipleOf": undefined,
            "name": "",
            "pattern": undefined,
            "properties": Array [],
            "template": null,
            "type": "number",
            "uniqueItems": undefined,
          },
          Object {
            "base": "boolean",
            "default": undefined,
            "deprecated": undefined,
            "description": null,
            "enum": Array [],
            "enums": Array [],
            "examples": Array [],
            "exclusiveMaximum": undefined,
            "exclusiveMinimum": undefined,
            "export": "generic",
            "format": undefined,
            "imports": Array [],
            "isDefinition": false,
            "isNullable": false,
            "isReadOnly": false,
            "isRequired": false,
            "link": null,
            "maxItems": undefined,
            "maxLength": undefined,
            "maxProperties": undefined,
            "maximum": undefined,
            "minItems": undefined,
            "minLength": undefined,
            "minProperties": undefined,
            "minimum": undefined,
            "multipleOf": undefined,
            "name": "",
            "pattern": undefined,
            "properties": Array [],
            "template": null,
            "type": "boolean",
            "uniqueItems": undefined,
          },
        ],
        "template": null,
        "type": "any",
        "uniqueItems": undefined,
      },
      "maxItems": undefined,
      "maxLength": undefined,
      "maxProperties": 8,
      "maximum": undefined,
      "minItems": undefined,
      "minLength": undefined,
      "minProperties": undefined,
      "minimum": undefined,
      "multipleOf": undefined,
      "name": "Metadata",
      "pattern": undefined,
      "properties": Array [],
      "template": null,
      "type": "any",
      "uniqueItems": undefined,
    }
  `);
});

test("getModel with Petstore User schema", async () => {
  const doc = await loadSpecFromFixtureFile("./tests/fixtures/specs/v3/petstore.json");

  invariant(doc, "doc should not be null");

  const model = getModelV3(doc, "User", {
    type: "object",
    properties: {
      id: {
        type: "integer",
        format: "int64",
        example: 10,
      },
      username: {
        type: "string",
        example: "theUser",
      },
      firstName: {
        type: "string",
        example: "John",
      },
      lastName: {
        type: "string",
        example: "James",
        deprecated: true,
      },
      email: {
        type: "string",
        example: "john@email.com",
      },
      password: {
        type: "string",
        example: "12345",
      },
      phone: {
        type: "string",
        example: "12345",
      },
      userStatus: {
        type: "integer",
        description: "User Status",
        format: "int32",
        example: 1,
      },
    },
    xml: {
      name: "user",
    },
  });

  expect(model).toMatchInlineSnapshot(`
    Object {
      "base": "any",
      "deprecated": undefined,
      "description": null,
      "enum": Array [],
      "enums": Array [],
      "examples": Array [],
      "exclusiveMaximum": undefined,
      "exclusiveMinimum": undefined,
      "export": "interface",
      "format": undefined,
      "imports": Array [],
      "isDefinition": false,
      "isNullable": false,
      "isReadOnly": false,
      "isRequired": false,
      "link": null,
      "maxItems": undefined,
      "maxLength": undefined,
      "maxProperties": undefined,
      "maximum": undefined,
      "minItems": undefined,
      "minLength": undefined,
      "minProperties": undefined,
      "minimum": undefined,
      "multipleOf": undefined,
      "name": "User",
      "pattern": undefined,
      "properties": Array [
        Object {
          "additionalProperties": undefined,
          "base": "number",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            10,
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": "int64",
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "id",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "number",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            "theUser",
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "username",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            "John",
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "firstName",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": true,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            "James",
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "lastName",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            "john@email.com",
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "email",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            "12345",
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "password",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            "12345",
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "phone",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "number",
          "deprecated": undefined,
          "description": "User Status",
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            1,
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": "int32",
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "userStatus",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "number",
          "uniqueItems": undefined,
        },
      ],
      "template": null,
      "type": "any",
      "uniqueItems": undefined,
    }
  `);
});

test("getModel with Petstore Order schema", async () => {
  const doc = await loadSpecFromFixtureFile("./tests/fixtures/specs/v3/petstore.json");

  invariant(doc, "doc should not be null");

  const model = getModelV3(
    doc,
    "Order",
    {
      type: "object",
      properties: {
        id: {
          type: "integer",
          format: "int64",
          example: 10,
        },
        petId: {
          type: "integer",
          format: "int64",
          example: 198772,
        },
        quantity: {
          type: "integer",
          format: "int32",
          example: 7,
        },
        shipDate: {
          type: "string",
          format: "date-time",
        },
        status: {
          type: "string",
          description: "Order Status",
          example: "approved",
          enum: ["placed", "approved", "delivered"],
        },
        complete: {
          type: "boolean",
        },
      },
      xml: {
        name: "order",
      },
    },
    true,
  );

  expect(model).toMatchInlineSnapshot(`
    Object {
      "base": "any",
      "deprecated": undefined,
      "description": null,
      "enum": Array [],
      "enums": Array [
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": "Order Status",
          "enum": Array [
            Object {
              "description": null,
              "name": "PLACED",
              "type": "string",
              "value": "'placed'",
            },
            Object {
              "description": null,
              "name": "APPROVED",
              "type": "string",
              "value": "'approved'",
            },
            Object {
              "description": null,
              "name": "DELIVERED",
              "type": "string",
              "value": "'delivered'",
            },
          ],
          "enums": Array [],
          "examples": Array [
            "approved",
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "enum",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "status",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
      ],
      "examples": Array [],
      "exclusiveMaximum": undefined,
      "exclusiveMinimum": undefined,
      "export": "interface",
      "format": undefined,
      "imports": Array [],
      "isDefinition": true,
      "isNullable": false,
      "isReadOnly": false,
      "isRequired": false,
      "link": null,
      "maxItems": undefined,
      "maxLength": undefined,
      "maxProperties": undefined,
      "maximum": undefined,
      "minItems": undefined,
      "minLength": undefined,
      "minProperties": undefined,
      "minimum": undefined,
      "multipleOf": undefined,
      "name": "Order",
      "pattern": undefined,
      "properties": Array [
        Object {
          "additionalProperties": undefined,
          "base": "number",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            10,
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": "int64",
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "id",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "number",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "number",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            198772,
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": "int64",
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "petId",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "number",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "number",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            7,
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": "int32",
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "quantity",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "number",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": "date-time",
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "shipDate",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": "Order Status",
          "enum": Array [
            Object {
              "description": null,
              "name": "PLACED",
              "type": "string",
              "value": "'placed'",
            },
            Object {
              "description": null,
              "name": "APPROVED",
              "type": "string",
              "value": "'approved'",
            },
            Object {
              "description": null,
              "name": "DELIVERED",
              "type": "string",
              "value": "'delivered'",
            },
          ],
          "enums": Array [],
          "examples": Array [
            "approved",
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "enum",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "status",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "boolean",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "complete",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "boolean",
          "uniqueItems": undefined,
        },
      ],
      "template": null,
      "type": "any",
      "uniqueItems": undefined,
    }
  `);
});

test("getModel with PetStore Customer schema", async () => {
  const doc = await loadSpecFromFixtureFile("./tests/fixtures/specs/v3/petstore.json");

  invariant(doc, "doc should not be null");

  const model = getModelV3(doc, "Customer", {
    type: "object",
    properties: {
      id: {
        type: "integer",
        format: "int64",
        example: 100000,
      },
      username: {
        type: "string",
        example: "fehguy",
      },
      address: {
        type: "array",
        items: {
          $ref: "#/components/schemas/Address",
        },
      },
    },
  });

  expect(model).toMatchInlineSnapshot(`
    Object {
      "base": "any",
      "deprecated": undefined,
      "description": null,
      "enum": Array [],
      "enums": Array [],
      "examples": Array [],
      "exclusiveMaximum": undefined,
      "exclusiveMinimum": undefined,
      "export": "interface",
      "format": undefined,
      "imports": Array [
        "Address",
      ],
      "isDefinition": false,
      "isNullable": false,
      "isReadOnly": false,
      "isRequired": false,
      "link": null,
      "maxItems": undefined,
      "maxLength": undefined,
      "maxProperties": undefined,
      "maximum": undefined,
      "minItems": undefined,
      "minLength": undefined,
      "minProperties": undefined,
      "minimum": undefined,
      "multipleOf": undefined,
      "name": "Customer",
      "pattern": undefined,
      "properties": Array [
        Object {
          "additionalProperties": undefined,
          "base": "number",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            100000,
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": "int64",
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "id",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "number",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            "fehguy",
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "username",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "Address",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "array",
          "format": undefined,
          "imports": Array [
            "Address",
          ],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "address",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "Address",
          "uniqueItems": undefined,
        },
      ],
      "template": null,
      "type": "any",
      "uniqueItems": undefined,
    }
  `);
});

test("getModel with Petstore Pet schema", async () => {
  const doc = await loadSpecFromFixtureFile("./tests/fixtures/specs/v3/petstore.json");

  invariant(doc, "doc should not be null");

  const model = getModelV3(doc, "Pet", {
    required: ["name", "photoUrls"],
    type: "object",
    properties: {
      id: {
        type: "integer",
        format: "int64",
        example: 10,
      },
      name: {
        type: "string",
        example: "doggie",
      },
      category: {
        $ref: "#/components/schemas/Category",
      },
      photoUrls: {
        type: "array",
        xml: {
          wrapped: true,
        },
        items: {
          type: "string",
          xml: {
            name: "photoUrl",
          },
        },
      },
      tags: {
        type: "array",
        xml: {
          wrapped: true,
        },
        items: {
          $ref: "#/components/schemas/Tag",
        },
      },
      status: {
        type: "string",
        description: "pet status in the store",
        enum: ["available", "pending", "sold"],
      },
    },
  });

  expect(model).toMatchInlineSnapshot(`
    Object {
      "base": "any",
      "deprecated": undefined,
      "description": null,
      "enum": Array [],
      "enums": Array [
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": "pet status in the store",
          "enum": Array [
            Object {
              "description": null,
              "name": "AVAILABLE",
              "type": "string",
              "value": "'available'",
            },
            Object {
              "description": null,
              "name": "PENDING",
              "type": "string",
              "value": "'pending'",
            },
            Object {
              "description": null,
              "name": "SOLD",
              "type": "string",
              "value": "'sold'",
            },
          ],
          "enums": Array [],
          "examples": Array [],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "enum",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "status",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
      ],
      "examples": Array [],
      "exclusiveMaximum": undefined,
      "exclusiveMinimum": undefined,
      "export": "interface",
      "format": undefined,
      "imports": Array [
        "Category",
        "Tag",
      ],
      "isDefinition": false,
      "isNullable": false,
      "isReadOnly": false,
      "isRequired": false,
      "link": null,
      "maxItems": undefined,
      "maxLength": undefined,
      "maxProperties": undefined,
      "maximum": undefined,
      "minItems": undefined,
      "minLength": undefined,
      "minProperties": undefined,
      "minimum": undefined,
      "multipleOf": undefined,
      "name": "Pet",
      "pattern": undefined,
      "properties": Array [
        Object {
          "additionalProperties": undefined,
          "base": "number",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            10,
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": "int64",
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "id",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "number",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [
            "doggie",
          ],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "generic",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": true,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "name",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
        Object {
          "base": "Category",
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "export": "reference",
          "imports": Array [
            "Category",
          ],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "name": "category",
          "properties": Array [],
          "template": null,
          "type": "Category",
        },
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "array",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": true,
          "link": Object {
            "base": "string",
            "default": undefined,
            "deprecated": undefined,
            "description": null,
            "enum": Array [],
            "enums": Array [],
            "examples": Array [],
            "exclusiveMaximum": undefined,
            "exclusiveMinimum": undefined,
            "export": "generic",
            "format": undefined,
            "imports": Array [],
            "isDefinition": false,
            "isNullable": false,
            "isReadOnly": false,
            "isRequired": false,
            "link": null,
            "maxItems": undefined,
            "maxLength": undefined,
            "maxProperties": undefined,
            "maximum": undefined,
            "minItems": undefined,
            "minLength": undefined,
            "minProperties": undefined,
            "minimum": undefined,
            "multipleOf": undefined,
            "name": "",
            "pattern": undefined,
            "properties": Array [],
            "template": null,
            "type": "string",
            "uniqueItems": undefined,
          },
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "photoUrls",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "Tag",
          "deprecated": undefined,
          "description": null,
          "enum": Array [],
          "enums": Array [],
          "examples": Array [],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "array",
          "format": undefined,
          "imports": Array [
            "Tag",
          ],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "tags",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "Tag",
          "uniqueItems": undefined,
        },
        Object {
          "additionalProperties": undefined,
          "base": "string",
          "deprecated": undefined,
          "description": "pet status in the store",
          "enum": Array [
            Object {
              "description": null,
              "name": "AVAILABLE",
              "type": "string",
              "value": "'available'",
            },
            Object {
              "description": null,
              "name": "PENDING",
              "type": "string",
              "value": "'pending'",
            },
            Object {
              "description": null,
              "name": "SOLD",
              "type": "string",
              "value": "'sold'",
            },
          ],
          "enums": Array [],
          "examples": Array [],
          "exclusiveMaximum": undefined,
          "exclusiveMinimum": undefined,
          "export": "enum",
          "format": undefined,
          "imports": Array [],
          "isDefinition": false,
          "isNullable": false,
          "isReadOnly": false,
          "isRequired": false,
          "link": null,
          "maxItems": undefined,
          "maxLength": undefined,
          "maxProperties": undefined,
          "maximum": undefined,
          "minItems": undefined,
          "minLength": undefined,
          "minProperties": undefined,
          "minimum": undefined,
          "multipleOf": undefined,
          "name": "status",
          "pattern": undefined,
          "properties": Array [],
          "template": null,
          "type": "string",
          "uniqueItems": undefined,
        },
      ],
      "template": null,
      "type": "any",
      "uniqueItems": undefined,
    }
  `);
});
